package e

const (
	SUCCESS        = 200
	ERROR          = 500
	INVALID_PARAMS = 400

	ERROR_EXIST_TAG         = 101
	ERROR_NOT_EXIST_TAG     = 102
	ERROR_NOT_EXIST_ARTICLE = 103

	ERROR_AUTH_CHECK_TOKEN_FAIL    = 201
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT = 202
	ERROR_AUTH_TOKEN               = 203
	ERROR_AUTH                     = 204
)
